services:
  wiremock:
    image: "wiremock/wiremock:3.9.1"
    container_name: carousel_wiremock
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/extensions:/var/wiremock/extensions
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
    healthcheck:
      test: curl -f http://localhost:8080/__admin/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
  node:
    container_name: carousel_node
    restart: always
    build: .
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    depends_on:
      wiremock:
        condition: service_healthy